
environments:
   -
      name: "cd"
      title:
        label: "Continuous Delivery"
        pipeline: false
        provision: false
        order:
          -
            product: "M2GB_D40GB"
            image: "centos-7-x64"
            qty: 1
            segment: "ci"
            label: "CD Core"
          -
            product: "M4GB_D60GB"
            image: "centos-7-x64"
            qty: 1
            segment: "reg"
            label: "Pipeline Mgmt"
          -
            product: "M2GB_D40GB"
            image: "centos-7-x64"
            qty: 1
            segment: "builder"
            label: "Builders"
          -
            product: "M2GB_D40GB"
            image: "centos-7-x64"
            qty: 1
            segment: "col"
            label: "Collaboration"
          -
            product: "M1GB_D25GB"
            image: "centos-7-x64"
            qty: 1
            segment: "vpn"
            label: "VPN"

   -
      name: "mon"
      title:
        label: "Monitoring & Analytics"
        pipeline: false
        provision: false
        order:
          -
            product: "M4GB_D60GB"
            image: "centos-7-x64"
            qty: 1
            segment: "mon"
            label: "Monitoring"
          -
            product: "M4GB_D60GB"
            image: "centos-7-x64"
            qty: 1
            segment: "kib"
            label: "Kibana Analysis"

   -
      name: "play"
      title:
        label: "Playground"
        pipeline: false
        provision: false
        order:
          -
            product: "M4GB_D60GB"
            image: "centos-7-x64"
            qty: 1
            segment: "tools"
            label: "Tools"
          -
            product: "M16GB_D160GB"
            image: "centos-7-x64"
            qty: 1
            segment: "bigdata"
            label: "Big Data"
          -
            product: "M8GB_D80GB"
            image: "centos-7-x64"
            qty: 1
            segment: "nextgen"
            label: "Next Generation"

   -
      name: "intg"
      title:
        label: "Integration"
        pipeline: true
        provision: false
        order:
          -
            product: "M2GB_D40GB"
            image: "centos-7-x64"
            qty: 3
            segment: "db"
            label: "DB"
          -
            product: "M4GB_D60GB"
            image: "centos-7-x64"
            qty: 1
            segment: "app"
            label: "App"

   -
      name: "stage"
      title:
        label: "Staging"
        pipeline: true
        provision: false
        order:
          -
            product: "M2GB_D40GB"
            image: "centos-7-x64"
            qty: 3
            segment: "db"
            label: "DB"
          -
            product: "M4GB_D60GB"
            image: "centos-7-x64"
            qty: 1
            segment: "app"
            label: "App"
          -
            product: "M1GB_D25GB"
            image: "centos-7-x64"
            qty: 1
            segment: "lb"
            label: "Load Balancer"


   -
      name: "live"
      title:
        label: "Live"
        pipeline: true
        provision: false
        order:
          -
            product: "M4GB_D60GB"
            image: "centos-7-x64"
            qty: 1
            segment: "app"
            label: "App"
          -
            product: "M1GB_D25GB"
            image: "centos-7-x64"
            qty: 1
            segment: "lb"
            label: "Load Balancer"
