format_version: 3
pipelines:
    ${tenant_id}-${project}-${workspace}:
        group: ${tenant_id}
        environment_variables:
            PROJECT: ${project}
            TENANT: ${tenant_id}
        materials:
            charts:
                git: https://gitlab.com/ikethecoder/helm-charts.git
                branch: develop
                auto_update: false
            myupstream:
                pipeline: ${tenant_id}-${project}
                stage: deploy

        stages:
        - vault:
            clean_workspace: true
            elastic_profile_id: vault
            artifacts:
            - build:
                source: kube_config
                destination: artifacts
            - build:
                source: env.yaml
                destination: artifacts
            - build:
                source: s3cfg
                destination: artifacts
            tasks:
            - script: |
                vault status

                export VAULT_TOKEN=$(vault write -field token auth/approle/login \
                    role_id=$VAULT_ROLE_ID \
                    secret_id=$VAULT_SECRET_ID)

                vault read -field kube_raw_config secret/tenants/${tenant_id}/${workspace}/cluster > kube_config
                vault read -field data -format yaml secret/tenants/${tenant_id}/${workspace}/services/${project} > env.yaml
                vault read -field data -format json secret/tenants/${tenant_id}/${workspace}/providers/do_s3 > s3cfg

        - deploy:
            clean_workspace: true
            elastic_profile_id: helm321
            tasks:
            - fetch:
                pipeline: ${tenant_id}-${project}-${workspace}
                stage: vault
                job: vault
                source: artifacts
                destination: .

            - script: |

                mkdir -p ~/.kube

                cat artifacts/kube_config | base64 -d > ~/.kube/config

                PARAMS_FROM_VAULT=`cat artifacts/env.yaml | fold -w 200 | awk '{ printf "%4s%s\n","",$0 }'`

                echo "

                replicaCount: 1

                app:
                $PARAMS_FROM_VAULT
                    version: \"$GO_DEPENDENCY_LABEL_MYUPSTREAM\"

                nodeSelector:
                    doks.digitalocean.com/node-pool: ${es_id}-${deploy_workspace}-pool

                image:
                    repository: registry.ops.${domain_name}/${tenant_id}/${project}
                    tag: $GO_DEPENDENCY_LABEL_MYUPSTREAM
                    pullPolicy: Always

                ingress:
                    enabled: true
                    hosts:
                    - host: ${dns_prefix}.${deploy_workspace}.ws.${domain_name}
                      paths: ["/"]

                persistence:
                    enabled: true
                
                
                " > values.local.yaml

                cat values.local.yaml

                helm upgrade $PROJECT --install --recreate-pods --namespace apps -f ./values.local.yaml $PROJECT/.
                

