name: rocketchat
version: 0.69.2
resources:
  - service_discovery_service:
      rocketchat:
        Name: rocketchat
        Address: "${d}{var.compute_instance.${instance.name}.privateIp}"
        Port: 8780
        Tags: [ "${instance.id}", "${environment.id}", "collaboration" ]
        Check:
          http: "http://${d}{var.compute_instance.${instance.name}.privateIp}:8780"
          interval: 10s
          timeout: 1s

  - digitalocean_dns:
      chat:
        environment: "cd"
        droplet: "${instance.name}"
        domain-id: "${es.fqdn_id}"
        domain: "${es.fqdn}"
        a:
          name: "chat"
          address: "${d}{digitalocean_droplet.${es.tag}-cd-ci-01.ipv4_address}"

  - proxy_ssl_virtual_host:
      chat:
        environment: cd
        serverNumber: 1
        segment: ci
        privateKey: "master_key"
        domainName: "chat.${es.fqdn}"
        domains: "${es.fqdn},chat.${es.fqdn}"
        certname: "${es.fqdn}"
        email: "${owner.email}"

  - proxy_service:
      rocketchat:
        environment: "cd"
        serverNumber: 1
        segment: "ci"
        privateKey: "master_key"
        proxy_ssl_virtual_host: "chat"
        location: "/"
        passthrough: "http://${d}{var.compute_instance.${instance.name}.privateIp}:8780"


  - service_endpoint:
      ${instance.id}-rocketchat:
        service: rocketchat
        instance: ${instance.id}
        environment: ${environment.id}
        segment: ${segment.id}
        type: console
        secure: "https://chat.${es.fqdn}"

  - vault_secret:
      service/rocketchat/esadmin/credentials:
        user_name: esadmin
        password: ${utils.randomPassword}
        email: ${owner.email}
        url: "https://chat.${es.fqdn}"

  - vault_secret:
      oauth/clients/rocketchat:
        label: "Rocket.Chat"
        client_secret: "${utils.uuid}"
        accessTokenLifetime: 14515200
        oauth2_root: "https://${es.fqdn}/gw"
        oauth2_authorize: "https://${es.fqdn}/gw/oauth/authorize"
        oauth2_token: "https://${es.fqdn}/gw/oauth/token"
        oauth2_profile: "https://${es.fqdn}/gw/me"
        grants:
        - "password"
        - "authorization_code"
        - "refresh_token"
        redirectUris:
        - "https://chat.${es.fqdn}/_oauth/esgw"
