name: grafana
version: tbd
resources:
  - service_discovery_service:
      ${instance.id}-grafana:
        Name: grafana
        Address: "${d}{var.compute_instance.${instance.name}.privateIp}"
        Port: 3000
        Tags: [ "${instance.id}", "${environment.id}", "monitoring" ]
        Check:
          http: "http://${d}{var.compute_instance.${instance.name}.privateIp}:3000/grafana/login"
          interval: 10s
          timeout: 1s

  - service_endpoint:
      ${instance.id}-grafana:
        service: grafana
        instance: ${instance.id}
        environment: ${environment.id}
        segment: ${segment.id}
        type: console
        secure: "https://${es.fqdn}/grafana"

  - proxy_service:
      grafana:
        environment: cd
        serverNumber: 1
        segment: ci
        privateKey: master_key
        proxy_ssl_virtual_host: default
        location: "/grafana/"
        passthrough: "http://${d}{ecosystem.lookupInstanceByName('${instance.id}').privateIp}:3000/"

  - vault_secret:
      service/grafana/esadmin/credentials:
        user_name: admin
        password: admin1admin1
        email: ${owner.email}
        url: "https://${es.fqdn}/grafana/"

  - vault_secret:
      oauth/clients/grafana:
        label: "Grafana"
        client_secret: "11-11-11-11"
        accessTokenLifetime: 14515200
        oauth2_root_url: "https://${es.fqdn}/gw"
        oauth2_authorize: "https://${es.fqdn}/gw/oauth/authorize"
        oauth2_token: "https://${es.fqdn}/gw/oauth/token"
        oauth2_profile: "https://${es.fqdn}/gw/me"
        grants:
        - "password"
        - "authorization_code"
        - "refresh_token"
        redirectUris:
        - "https://${es.fqdn}/grafana/oauth/callback"