format_version: 3
pipelines:
  ${tenant_id}-rpa-channel:
    group: ${tenant_id}-rpa
    environment_variables:
      PROJECT: rpa-channel
      TENANT: ${tenant_id}
    label_template: "$${source[:8]}"
    lock_behavior: none
    materials:
      source:
        git: https://github.com/canzea-lab/rpa-channel.git
        auto_update: false
        branch: develop
    stages:
    - build:
        clean_workspace: true
        elastic_profile_id: "nodejs8"
        artifacts:
        - build:
           source: node_modules
           destination: artifacts
        tasks:
        - script: |
            npm install            

    - deploy:
        clean_workspace: true
        elastic_profile_id: docker
        tasks:
        - fetch:
            pipeline: ${tenant_id}-rpa-channel
            stage: build
            job: build
            source: artifacts
            destination: .
        - script: |
            echo "

              FROM node:10-slim

              WORKDIR /app

              COPY artifacts/node_modules node_modules
              COPY src .
              COPY package.json ./

              EXPOSE 80

              ENTRYPOINT npm start

            " > Dockerfile

            ls -l artifacts

            docker build --tag $PROJECT.local .
            docker tag $PROJECT.local $REGISTRY/$TENANT/$PROJECT:latest
            docker tag $PROJECT.local $REGISTRY/$TENANT/$PROJECT:$GO_PIPELINE_LABEL
            docker push $REGISTRY/$TENANT/$PROJECT
