
environments:
   -
      name: "cd"
      title:
        label: "Continuous Delivery"
        pipeline: false
        provision: false
        order:
          -
            product: "M4GB_D60GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "ci"
            label: "Pipeline Mgmt"
          -
            product: "M2GB_D40GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "builder"
            label: "Builders"
          -
            product: "M4GB_D60GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "col"
            label: "Collaboration"
          -
            product: "M4GB_D60GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "sc"
            label: "GitLab"

   -
      name: "play"
      title:
        label: "Playground"
        pipeline: false
        provision: false
        order:
          -
            product: "M4GB_D60GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "tools"
            label: "Tools"
          -
            product: "M4GB_D60GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "nifi"
            label: "Apache NIFI"


   -
      name: "mon"
      title:
        label: "Monitoring & Analytics"
        pipeline: false
        provision: false
        order:
          -
            product: "M4GB_D60GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "mon"
            label: "Monitoring"
          -
            product: "M4GB_D60GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "kib"
            label: "Kibana Analysis"

   -
      name: "intg"
      title:
        label: "Integration"
        pipeline: true
        provision: true
        order:
          -
            product: "M2GB_D40GB"
            image: "centos-7-2-x64"
            qty: 3
            segment: "db"
            label: "DB"
          -
            product: "M4GB_D60GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "app"
            label: "App"

   -
      name: "perf"
      title:
        label: "Performance"
        pipeline: true
        provision: false
        order:
          -
            product: "M2GB_D40GB"
            image: "centos-7-2-x64"
            qty: 3
            segment: "db"
            label: "DB"
          -
            product: "M4GB_D60GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "app"
            label: "App"

   -
      name: "uat"
      title:
        label: "Acceptance"
        pipeline: true
        provision: false
        order:
          -
            product: "M2GB_D40GB"
            image: "centos-7-2-x64"
            qty: 3
            segment: "db"
            label: "DB"
          -
            product: "M4GB_D60GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "app"
            label: "App"
   -
      name: "live"
      title:
        label: "Live"
        pipeline: true
        provision: false
        order:
          -
            product: "M4GB_D60GB"
            image: "centos-7-2-x64"
            qty: 1
            segment: "app"
            label: "App"
