name: gitea
version: 1.5.1
resources:
- service_endpoint:
    ${instance.id}-gitea:
      service: gitea
      instance: ${instance.id}
      environment: ${environment.id}
      segment: ${segment.id}
      type: console
      secure: "https://sc.${es.fqdn}"


- service_discovery_service_md:
    gitea:
      role: "sourcecontrol"
      solution: "gitea/docker"
      environment: "cd"
      serverNumber: 1
      segment: "ci"
      privateKey: "master_key"

- vault_secret:
    service/gitea/esadmin/credentials:
      wire: "vault:register-secret"
      environment: "cd"
      serverNumber: 1
      segment: "ci"
      privateKey: "master_key"
      key: "service/gitea/esadmin/credentials"
      data:
        user_name: "esadmin"
        password: "${utils.randomPassword}"
        email: "${owner.email}"
        url: "https://sc.${es.fqdn}"

- vault_secret:
    oauth/clients/gitea:
      wire: "vault:register-secret"
      environment: "cd"
      serverNumber: 1
      segment: "ci"
      privateKey: "master_key"
      key: "oauth/clients/gitea"
      data:
        label: "Gitea"
        client_secret: "${utils.uuid}"
        oidc_issuer: "https://identity.${es.fqdn}/auth/realms/ecosystem"
        oidc_discovery: "https://identity.${es.fqdn}/auth/realms/ecosystem/.well-known/openid-configuration"

- boot:first-config:
    gitea:
      wire: "gitea:first-config"
      environment: "cd"
      serverNumber: 1
      segment: "ci"
      privateKey: "master_key"

- boot:first-login:
    gitea:
      wire: "gitea:first-login"
      environment: "cd"
      serverNumber: 1
      segment: "ci"
      privateKey: "master_key"

- boot:first-set-oauth:
    gitea:
      wire: "gitea:first-set-oauth"
      environment: "cd"
      serverNumber: 1
      segment: "ci"
      privateKey: "master_key"
