name: minio
version: RELEASE.2018-09-12T18-49-56Z
resources:
- service_discovery_service:
    ${instance.id}-minio:
      Name: ${environment.id}-minio
      Address: "${d}{var.compute_instance.${instance.name}.privateIp}"
      Port: 9000
      Tags: [ "${instance.id}", "${environment.id}", "object_storage" ]

- vault_secret:
    providers/minio/live:
      access_key: admin
      secret_key: ${utils.randomPassword}
      mode: server
      data_path: /data
      gateway_provider: none
      email: ${owner.email}
      url: "https://identity.${es.fqdn}"

- vault_secret:
    shell/commands/${instance.id}-minio:
      user: "root"
      host: "${d}{ecosystem.lookupInstanceByName('${instanceId}').privateIp}"
      auth: "publickey"
      identity: "/home/pm2user/ssl/keys/root_id_rsa"
      command: "docker run -it --entrypoint=/bin/sh minio/mc"
      interactive: true

- service_endpoint:
    ${instance.id}-minio:
      service: minio
      instance: ${instance.id}
      environment: ${environment.id}
      segment: ${segment.id}
      type: console
      icon: "fas fa-terminal"
      secure: "https://${es.fqdn}/shell/${instance.id}-minio"

