name: flows-gateway
version: 0.1.35
resources:
- service_endpoint:
    ${instance.id}-flows-gateway:
      service: nodered
      instance: ${instance.id}
      environment: ${environment.id}
      segment: ${segment.id}
      type: console
      secure: "https://${es.fqdn}/gwadmin"

- service_discovery_service_md:
    flows-gateway:
      role: "adhoc"
      solution: "flows-gateway/docker"
      environment: "cd"
      serverNumber: 1
      segment: "ci"
      privateKey: "master_key"

- vault_secret:
    oauth/clients/flows-gateway:
      wire: "vault:register-secret"
      environment: "cd"
      serverNumber: 1
      segment: "ci"
      privateKey: "master_key"
      key: "oauth/clients/flows-gateway"
      data:
        label: "Flows Gateway"
        client_secret: "${utils.uuid}"
        accessTokenLifetime: 14515200
        oauth2_authorize: "https://${es.fqdn}/gw/oauth/authorize"
        oauth2_token: "https://${es.fqdn}/gw/oauth/token"
        oauth2_profile: "https://${es.fqdn}/gw/me"
        grants:
        - "password"
        - "authorization_code"
        - "refresh_token"
        redirectUris:
        - "https://${es.fqdn}/gwadmin/auth/strategy/callback"

- vault_secret:
    service/flows-gateway/esadmin/credentials:
      wire: "vault:register-secret"
      environment: "cd"
      serverNumber: 1
      segment: "ci"
      privateKey: "master_key"
      key: "service/flows-gateway/esadmin/credentials"
      data:
        user_name: "esadmin"
        password: "${utils.randomPassword}"
        email: "${owner.email}"
        url: "https://${es.fqdn}/gwadmin"

- boot:first-config:
    flows-gateway:
      wire: "flows-gateway:first-config"
      environment: "cd"
      serverNumber: 1
      segment: "ci"
      privateKey: "master_key"

