name: gocd
version: v18.7.0
resources:
  - service_discovery_service:
      gocd:
        Name: gocd
        Address: "${d}{var.compute_instance.${instance.name}.privateIp}"
        Port: 8153
        Tags: [ "${instance.id}", "${environment.id}", "delivery_pipeline" ]
        Check:
          http: "http://${d}{var.compute_instance.${instance.name}.privateIp}:8153"
          interval: 10s
          timeout: 1s

  - proxy_service:
      gocd:
        environment: cd
        serverNumber: 1
        segment: ci
        privateKey: master_key
        proxy_ssl_virtual_host: default
        location: "/go/"
        passthrough: "https://${d}{ecosystem.lookupInstanceByName('${instance.id}').privateIp}:8154"

  - service_endpoint:
      ${instance.id}-gocd:
        service: gocd
        instance: ${instance.id}
        environment: ${environment.id}
        segment: ${segment.id}
        type: console
        secure: "https://${es.fqdn}/go/admin/pipelines"

  - vault_secret:
      oauth/clients/gocd:
        label: "Go.CD"
        client_secret: "11-11-11-11"
        accessTokenLifetime: 14515200
        oauth2_root_url: "https://${es.fqdn}/gw"
        oauth2_authorize: "https://${es.fqdn}/gw/oauth/authorize"
        oauth2_token: "https://${es.fqdn}/gw/oauth/token"
        oauth2_profile: "https://${es.fqdn}/gw/me"
        grants:
        - "password"
        - "authorization_code"
        - "refresh_token"
        redirectUris:
        - "https://${es.fqdn}/go/plugin/cd.go.authorization.generic/authenticate"

  - vault_secret:
      service/gocd/sp_gocd_admin/credentials:
        password: "1234"
        email: "${owner.email}"

  - wire:
      gocd-first-set-oauth-apis:
        solution: gocd
        action: first-set-api-access
        droplet: "${es.tag}-cd-ci-01"

